# Classification of Structured Data with Keras preprocessing layers

**Author:** [Mike Fournigault](https://www.linkedin.com/in/mike-fournigault-57312071/)<br>


In [ ]:
import os
import sys

# Only the TensorFlow backend supports string inputs.
os.environ["KERAS_BACKEND"] = "tensorflow"

import numpy as np
import pandas as pd
import tensorflow as tf
import keras
from keras import layers

sys.path.append(os.path.abspath("../../src/"))

Adding the instrumentation of the TF code with debugger V2

In [4]:
tf.debugging.experimental.enable_dump_debug_info(
    dump_root="./tfdbg2_logdir", tensor_debug_mode="FULL_HEALTH", circular_buffer_size=-1
)

INFO:tensorflow:Enabled dumping callback in thread MainThread (dump root: ./tfdbg2_logdir, tensor debug mode: FULL_HEALTH)


## Loading and preparing the datasets

Reading and merging catalog and mapping files

In [5]:
columns = ["OBJECT_ID", "FITS_ID", "CCD_ID", "ISO0", "BACKGROUND", "ELLIPTICITY", "ELONGATION", "CLASS_STAR", "FLAGS", "EXPTIME"]
data_path = "../../data/"
proc_path = os.path.join(data_path, "processed")
fm_path = os.path.join(data_path, "for_modeling")


In [6]:
def custom_reader_func(datasets):
  return datasets.interleave(lambda x: x, num_parallel_calls=tf.data.AUTOTUNE)


In [7]:
# Load the tensorflow Datasets
print("current directory: ", os.getcwd())
print("Content of the directory: ", os.listdir(fm_path))
training_dataset = tf.data.Dataset.load(path=os.path.join(fm_path, "training_dataset"), reader_func=custom_reader_func)
validation_dataset = tf.data.Dataset.load(path=os.path.join(fm_path, "validation_dataset"), reader_func=custom_reader_func)
testing_dataset = tf.data.Dataset.load(path=os.path.join(fm_path, "test_dataset"), reader_func=custom_reader_func)

current directory:  /mnt/c/Users/mikef/git/astro_iqa/src/modeling
Content of the directory:  ['.gitattributes', 'map_images_labels.json', 'map_images_labels_cadc.json', 'map_images_labels_cadc2.json', 'map_images_labels_ngc0869.json', 'map_images_labels_ngc0896.json', 'map_images_labels_ngc7000.json', 'modelling.md', 'objects_catalog_cadc2.parquet.gz', 'objects_catalog_ngc0869.parquet.gz', 'objects_catalog_ngc0896.parquet.gz', 'objects_catalog_ngc7000.parquet.gz', 'test_dataset', 'training_dataset', 'validation_dataset']


2025-03-21 16:58:42.947773: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2025-03-21 16:58:43.180691: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2025-03-21 16:58:43.180751: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2025-03-21 16:58:43.184608: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2025-03-21 16:58:43.184907: I external/local_xla/xla/stream_executor

In [8]:
# As we separated the labels from the features, we need to convert the labels to StringLookups
label_lookup = tf.keras.layers.StringLookup()
label_lookup.adapt(training_dataset.map(lambda x, y: y))

training_dataset = training_dataset.map(lambda x, y: (x, label_lookup(y)))
validation_dataset = validation_dataset.map(lambda x, y: (x, label_lookup(y)))
testing_dataset = testing_dataset.map(lambda x, y: (x, label_lookup(y)))

In [9]:
from tensorflow.keras.layers import StringLookup, Normalization
from tensorflow.keras.utils import Sequence


#

Testing our datasets for sanity checks

In [10]:

[(train_features, label_batch)] = training_dataset.take(1)
print('Every feature:', list(train_features.keys()))
print('A batch of ELLIPTICITY:', train_features['ELLIPTICITY'])
print('A batch of targets:', label_batch )

Every feature: ['ISO0', 'FITS_ID', 'FLAGS', 'ELLIPTICITY', 'CCD_ID', 'CLASS_STAR', 'gt_label1', 'ELONGATION', 'EXPTIME', 'BACKGROUND']
A batch of ELLIPTICITY: tf.Tensor(
[[0.78264153]
 [0.47585982]
 [0.6671052 ]
 [0.17121279]
 [0.76049113]
 [0.7568648 ]
 [0.34455228]
 [0.7747539 ]
 [0.5960636 ]
 [0.51149046]
 [0.861753  ]
 [0.80339986]
 [0.29815495]
 [0.9918808 ]
 [0.9840157 ]
 [0.50382775]
 [0.9969438 ]
 [0.30246472]
 [0.72142637]
 [0.78332305]
 [0.05240852]
 [0.71980107]
 [0.6715517 ]
 [0.3731296 ]
 [0.7682065 ]
 [0.64978206]
 [0.0649904 ]
 [0.57324195]
 [0.7616688 ]
 [0.8111505 ]
 [0.7778587 ]
 [0.82150084]
 [0.84908044]
 [0.36903435]
 [0.7625987 ]
 [0.87358457]
 [0.50443614]
 [0.71031165]
 [0.8691399 ]
 [0.4297365 ]
 [0.5382836 ]
 [0.61038566]
 [0.57938814]
 [0.3192072 ]
 [0.9550641 ]
 [0.66174954]
 [0.78321755]
 [0.8423984 ]
 [0.63916516]
 [0.7373588 ]
 [0.8843243 ]
 [0.7907473 ]
 [0.6789378 ]
 [0.9104991 ]
 [0.5105925 ]
 [0.7571713 ]
 [0.43734515]
 [0.41002744]
 [0.7346002 ]
 [0.

In [11]:

[(validation_features, label_batch)] = validation_dataset.take(1)
print('Every feature:', list(validation_features.keys()))
print('A batch of ELLIPTICITY:', validation_features['ELLIPTICITY'])
print('A batch of targets:', label_batch )

Every feature: ['ISO0', 'FITS_ID', 'FLAGS', 'ELLIPTICITY', 'CCD_ID', 'CLASS_STAR', 'gt_label1', 'ELONGATION', 'EXPTIME', 'BACKGROUND']
A batch of ELLIPTICITY: tf.Tensor(
[[0.35624993]
 [0.26592666]
 [0.83772945]
 [0.7027589 ]
 [0.88597155]
 [0.7756514 ]
 [0.21023828]
 [0.7262485 ]
 [0.34354144]
 [0.6349837 ]
 [0.72408426]
 [0.59848714]
 [0.42157894]
 [0.866242  ]
 [0.5675301 ]
 [0.5993735 ]
 [0.2283591 ]
 [0.527534  ]
 [0.3625645 ]
 [0.31038666]
 [0.7874818 ]
 [0.5818038 ]
 [0.37114233]
 [0.4620301 ]
 [0.8003256 ]
 [0.64659506]
 [0.6382233 ]
 [0.47726828]
 [0.45862538]
 [0.18544888]
 [0.76987904]
 [0.39453256]
 [0.7794554 ]
 [0.5655196 ]
 [0.46227401]
 [0.645999  ]
 [0.2810517 ]
 [0.6341995 ]
 [0.6006255 ]
 [0.6220186 ]
 [0.870293  ]
 [0.6359205 ]
 [0.33743584]
 [0.31926966]
 [0.3068831 ]
 [0.6903769 ]
 [0.6277549 ]
 [0.88080883]
 [0.67995584]
 [0.5032791 ]
 [0.834937  ]
 [0.7598072 ]
 [0.9273336 ]
 [0.7901139 ]
 [0.57319057]
 [0.47191143]
 [0.07389432]
 [0.57480085]
 [0.7690511 ]
 [0.

In [12]:
print("testing dataset elements: ", testing_dataset.element_spec)
[(test_features, label_batch)] = testing_dataset.take(1)
print('Every feature:', list(test_features.keys()))
print('A batch of ELLIPTICITY:', test_features['ELLIPTICITY'])
# print("a batch of features: ", test_features)
print('A batch of targets:', label_batch )


testing dataset elements:  ({'ISO0': TensorSpec(shape=(None, 1), dtype=tf.float32, name=None), 'FITS_ID': TensorSpec(shape=(None, 1), dtype=tf.string, name=None), 'FLAGS': TensorSpec(shape=(None, 1), dtype=tf.int16, name=None), 'ELLIPTICITY': TensorSpec(shape=(None, 1), dtype=tf.float32, name=None), 'CCD_ID': TensorSpec(shape=(None, 1), dtype=tf.uint8, name=None), 'CLASS_STAR': TensorSpec(shape=(None, 1), dtype=tf.float32, name=None), 'gt_label1': TensorSpec(shape=(None, 1), dtype=tf.string, name=None), 'ELONGATION': TensorSpec(shape=(None, 1), dtype=tf.float32, name=None), 'EXPTIME': TensorSpec(shape=(None, 1), dtype=tf.float32, name=None), 'BACKGROUND': TensorSpec(shape=(None, 1), dtype=tf.float32, name=None)}, TensorSpec(shape=(None,), dtype=tf.int64, name=None))
Every feature: ['ISO0', 'FITS_ID', 'FLAGS', 'ELLIPTICITY', 'CCD_ID', 'CLASS_STAR', 'gt_label1', 'ELONGATION', 'EXPTIME', 'BACKGROUND']
A batch of ELLIPTICITY: tf.Tensor(
[[0.73774564]
 [0.76792455]
 [0.88322127]
 [0.5865227

In [13]:
# Fonction pour séparer les features et les labels
# def prepare_data(features, labels):
#     gt_label1 = labels['gt_label1']  # Récupérer la colonne cible
#     return features, gt_label1
# training_dataset = training_dataset.map(prepare_data)
# validation_dataset = validation_dataset.map(prepare_data)
# testing_dataset = testing_dataset.map(prepare_data)
# Prefetch the data
training_dataset = training_dataset.prefetch(buffer_size=tf.data.AUTOTUNE)
validation_dataset = validation_dataset.prefetch(buffer_size=tf.data.AUTOTUNE)
testing_dataset = testing_dataset.prefetch(buffer_size=tf.data.AUTOTUNE)

In [14]:
# from data_acquisition_understanding.dnn_datasets_preparation import read_and_concat_catalogs
# test_df = read_and_concat_catalogs([os.path.join(fm_path, "objects_catalog_ngc0869.parquet.gz")])

In [15]:
FEATURE_NAMES = [
    # "OBJECT_ID", # object
    "FITS_ID", # object
    "CCD_ID", # uint8
    "ISO0", # float32
    "BACKGROUND", # float32
    "ELLIPTICITY", # float32
    "ELONGATION", # float32
    "CLASS_STAR", # float32
    "FLAGS", # int16
    "EXPTIME", # float32
    "gt_label1" # object
]

NUMERIC_FEATURE_NAMES = {
    "ISO0": "float32",
    "BACKGROUND": "float32",
    "ELLIPTICITY": "float32",
    "ELONGATION": "float32",
    "CLASS_STAR": "float32",
    "EXPTIME": "float32"
}

CATEGORICAL_FEATURE_NAMES = {
    "FITS_ID": "string",
    "CCD_ID": "uint8",
    "FLAGS": "int16",
    # "gt_label1": "string" # is already part of the label
}

ID_COLUMNS = {
    "OBJECT_ID": "string"
}

## Create model inputs

In [16]:
def get_normalization_layer(name, dataset):
    print("Processing numerical feature: ", name)
    # Create a Normalization layer for the feature.
    normalizer = layers.Normalization(axis=None)

    # Prepare a Dataset that only yields the feature.
    feature_ds = dataset.map(lambda x, y: x[name])

    # Learn the statistics of the data.
    normalizer.adapt(feature_ds)

    return normalizer

In [17]:
def get_category_encoding_layer(name, dataset, dtype, max_tokens=None):
    # Create a layer that turns strings into integer indices.
    print("Processing categorical feature: ", name)
    if dtype == 'string':
        print(" ... StringLookup")
        index = layers.StringLookup(max_tokens=max_tokens)
    # Otherwise, create a layer that turns integer values into integer indices.
    else:
        print(" ... IntegerLookup")
        index = layers.IntegerLookup(max_tokens=max_tokens)

    # Prepare a `tf.data.Dataset` that only yields the feature.
    feature_ds = dataset.map(lambda x, y: x[name])

    # Learn the set of possible values and assign them a fixed integer index.
    index.adapt(feature_ds)

    # Encode the integer indices.
    encoder = layers.CategoryEncoding(num_tokens=index.vocabulary_size())

    # Apply multi-hot encoding to the indices. The lambda function captures the
    # layer, so you can use them, or include them in the Keras Functional model later.
    return lambda feature: encoder(index(feature))

## Encode input features

For categorical features, we encode them using `layers.Embedding` using the
`encoding_size` as the embedding dimensions. For the numerical features,
we apply linear transformation using `layers.Dense` to project each feature into
`encoding_size`-dimensional vector. Thus, all the encoded features will have the
same dimensionality.

In [18]:
def encode_inputs(dataset, numeric_headers, categorical_headers):

    all_inputs = {}
    encoded_features = []

    # Numerical features.
    for feat_name, dtype in numeric_headers.items():
        numeric_col = tf.keras.Input(shape=(1,), name=feat_name)
        normalization_layer = get_normalization_layer(feat_name, dataset)
        encoded_numeric_col = normalization_layer(numeric_col)
        all_inputs[feat_name] = numeric_col
        encoded_features.append(encoded_numeric_col)


    for feat_name, dtype in categorical_headers.items():
        categorical_col = tf.keras.Input(shape=(1,), name=feat_name, dtype=dtype)
        encoding_layer = get_category_encoding_layer(name=feat_name,
                                                    dataset=dataset,
                                                    dtype=dtype,
                                                    max_tokens=10)
        encoded_categorical_col = encoding_layer(categorical_col)
        all_inputs[feat_name] = categorical_col
        encoded_features.append(encoded_categorical_col)
    

    return all_inputs, encoded_features

In [19]:
# testing the function
all_inputs, encoded_features = encode_inputs(validation_dataset, NUMERIC_FEATURE_NAMES, CATEGORICAL_FEATURE_NAMES)

print("encoded features dypes: ", [x.dtype for x in encoded_features])

Processing numerical feature:  ISO0


2025-03-21 16:59:29.509260: I external/local_tsl/tsl/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory


Processing numerical feature:  BACKGROUND
Processing numerical feature:  ELLIPTICITY
Processing numerical feature:  ELONGATION
Processing numerical feature:  CLASS_STAR
Processing numerical feature:  EXPTIME
Processing categorical feature:  FITS_ID
 ... StringLookup
Processing categorical feature:  CCD_ID
 ... IntegerLookup
Processing categorical feature:  FLAGS
 ... IntegerLookup
encoded features dypes:  [tf.float32, tf.float32, tf.float32, tf.float32, tf.float32, tf.float32, tf.float32, tf.float32, tf.float32]


In [20]:
[(test_features, label_batch)] = testing_dataset.take(1)
test_ellip = test_features['ELLIPTICITY']
test_encod_ellip = get_normalization_layer("ELLIPTICITY", testing_dataset)
test_encod_ellip(test_ellip)

Processing numerical feature:  ELLIPTICITY


<tf.Tensor: shape=(128, 1), dtype=float32, numpy=
array([[ 1.2284503 ],
       [ 1.3497897 ],
       [ 1.8133597 ],
       [ 0.6204332 ],
       [-1.0678602 ],
       [ 0.32637793],
       [ 0.97721297],
       [ 1.406932  ],
       [ 1.9609343 ],
       [ 1.590036  ],
       [ 1.1273293 ],
       [ 1.6815034 ],
       [ 1.2027459 ],
       [-1.0518092 ],
       [-0.2405533 ],
       [ 0.02042446],
       [ 1.1894319 ],
       [ 1.4150672 ],
       [ 0.4331511 ],
       [ 0.93883413],
       [-0.17082123],
       [ 1.3351921 ],
       [ 0.13287951],
       [-0.79700536],
       [ 1.172977  ],
       [-0.37903488],
       [ 0.29318678],
       [ 1.9395019 ],
       [ 0.13663316],
       [ 1.3452564 ],
       [ 1.0009425 ],
       [ 0.7916211 ],
       [ 0.20184423],
       [-0.0476176 ],
       [ 0.95010537],
       [ 0.7475537 ],
       [ 0.11652456],
       [ 0.24605568],
       [ 0.7201779 ],
       [-1.1036808 ],
       [ 1.51507   ],
       [ 0.5456349 ],
       [ 0.8753409 ],
    

In [21]:
test_gt_label = test_features['FITS_ID']
test_encod_gt_label = get_category_encoding_layer("FITS_ID", testing_dataset, "string", 10)
test_encod_gt_label(test_gt_label)

Processing categorical feature:  FITS_ID
 ... StringLookup


<tf.Tensor: shape=(128, 10), dtype=float32, numpy=
array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]], dtype=float32)>

## Create Gated Residual and Variable Selection Networks model

In [23]:
def create_model(dataset, numeric_headers, categorical_headers,  
                 encoding_size=32, dropout_rate=0.15):
    """
    Create a model with embedding layers for categorical features.
    """
    all_inputs, encoded_inputs = encode_inputs(dataset, numeric_headers, categorical_headers)

    all_features = layers.concatenate(encoded_inputs)
    x = layers.Dense(32, activation="relu")(all_features)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(dropout_rate)(x)

    outputs = layers.Dense(units=5, activation="sigmoid")(x)
    model = keras.Model(inputs=all_inputs, outputs=outputs)

    return model


## Compile, train, and evaluate the model

In [24]:
learning_rate = 0.001
dropout_rate = 0.15
batch_size = 265
num_epochs = 20
encoding_size = 16

model = create_model(training_dataset, NUMERIC_FEATURE_NAMES, CATEGORICAL_FEATURE_NAMES, 
                 encoding_size, dropout_rate)


Processing numerical feature:  ISO0
Processing numerical feature:  BACKGROUND
Processing numerical feature:  ELLIPTICITY
Processing numerical feature:  ELONGATION
Processing numerical feature:  CLASS_STAR
Processing numerical feature:  EXPTIME
Processing categorical feature:  FITS_ID
 ... StringLookup
Processing categorical feature:  CCD_ID
 ... IntegerLookup
Processing categorical feature:  FLAGS
 ... IntegerLookup


In [25]:
model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=learning_rate),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

In [26]:
# Create an early stopping callback.
early_stopping = keras.callbacks.EarlyStopping(
    monitor="val_loss", patience=5, restore_best_weights=True
)

print("Start training the model...")

model.fit(
    training_dataset,
    epochs=num_epochs,
    validation_data=validation_dataset,
    # callbacks=[early_stopping],
)
print("Model training finished.")



Start training the model...
Epoch 1/20


/home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/functional.py:642: UserWarning: Input dict contained keys ['gt_label1'] which did not match any model input. They will be ignored by the model.
  inputs = self._flatten_to_reference_inputs(inputs)
2025-03-21 17:22:44.459362: I external/local_xla/xla/service/service.cc:168] XLA service 0x7f1665316a10 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2025-03-21 17:22:44.459496: I external/local_xla/xla/service/service.cc:176]   StreamExecutor device (0): Quadro P4000, Compute Capability 6.1
2025-03-21 17:22:44.465800: W tensorflow/core/framework/op_kernel.cc:1839] OP_REQUIRES failed at xla_ops.cc:574 : INVALID_ARGUMENT: Detected unsupported operations when trying to compile graph __inference__update_step_xla_279200[] on XLA_GPU_JIT: DebugNumericSummaryV2 (No registered 'DebugNumericSummaryV2' OpKernel for XLA_GPU_JIT devices compatible with node {{node DebugNumericS

InvalidArgumentError: Graph execution error:

Detected at node DebugNumericSummaryV2 defined at (most recent call last):
<stack traces unavailable>
Detected at node DebugNumericSummaryV2 defined at (most recent call last):
<stack traces unavailable>
Detected unsupported operations when trying to compile graph __inference__update_step_xla_279200[] on XLA_GPU_JIT: DebugNumericSummaryV2 (No registered 'DebugNumericSummaryV2' OpKernel for XLA_GPU_JIT devices compatible with node {{node DebugNumericSummaryV2}}){{node DebugNumericSummaryV2}}
The op is created at: 
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/runpy.py", line 197, in _run_module_as_main
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/runpy.py", line 87, in _run_code
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel_launcher.py", line 18, in <module>
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/traitlets/config/application.py", line 1075, in launch_instance
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 739, in start
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 205, in start
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/asyncio/events.py", line 80, in _run
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 534, in process_one
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/ipkernel.py", line 449, in do_execute
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3024, in run_cell
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3079, in _run_cell
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3284, in run_cell_async
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3466, in run_ast_nodes
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3526, in run_code
File "tmp/ipykernel_78405/2435027649.py", line 8, in <module>
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 65, in error_handler
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py", line 1807, in fit
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py", line 1401, in train_function
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py", line 1384, in step_function
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py", line 1373, in run_step
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/engine/training.py", line 1154, in train_step
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py", line 544, in minimize
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py", line 1223, in apply_gradients
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py", line 652, in apply_gradients
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py", line 1253, in _internal_apply_gradients
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py", line 1345, in _distributed_apply_gradients_fn
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/keras/src/optimizers/optimizer.py", line 1340, in apply_grad_to_update_var
File "home/mike/miniconda3/envs/astro_quality/lib/python3.9/site-packages/tensorflow/core/function/polymorphism/function_type.py", line 356, in placeholder_arguments
	tf2xla conversion failed while converting __inference__update_step_xla_279200[]. Run with TF_DUMP_GRAPH_PREFIX=/path/to/dump/dir and --vmodule=xla_compiler=2 to obtain a dump of the compiled functions.
	 [[Adam/StatefulPartitionedCall_4]] [Op:__inference_train_function_280210]

In [ ]:
print("Evaluating model performance...")
_, accuracy = model.evaluate(testing_dataset)
print(f"Test accuracy: {round(accuracy * 100, 2)}%")

You should achieve more than 95% accuracy on the test set.

To increase the learning capacity of the model, you can try increasing the
`encoding_size` value, or stacking multiple GRN layers on top of the VSN layer.
This may require to also increase the `dropout_rate` value to avoid overfitting.

**Example available on HuggingFace**

| Trained Model | Demo |
| :--: | :--: |
| [![Generic badge](https://img.shields.io/badge/%F0%9F%A4%97%20Model-Classification%20With%20GRN%20%26%20VSN-red)](https://huggingface.co/keras-io/structured-data-classification-grn-vsn) | [![Generic badge](https://img.shields.io/badge/%F0%9F%A4%97%20Space-Classification%20With%20GRN%20%26%20VSN-red)](https://huggingface.co/spaces/keras-io/structured-data-classification-grn-vsn) |