In [8]:
from astropy.io import fits
from astropy.table import Table

import numpy as np
import os


In [2]:
root_path = "/home/mike/git/computational_astro/astro_iqa"
data_path = "data/raw"
data_path = os.path.join(root_path, data_path)

# List all fits files in the data directory
fits_files = [f for f in os.listdir(data_path) if f.endswith(".fits.fz")]

In [3]:
# For each fits file, generate ldac file with sextractor
config_file = "xymfhe.sex"
for fits_file in fits_files:
    fits_path = os.path.join(data_path, fits_file)
    ldac_path = fits_path.replace(".fits.fz", ".ldac")
    if not os.path.exists(ldac_path):
        os.system("sex {} -c {}".format(fits_path, config_file))
        os.system("mv {} {}".format("test.cat", ldac_path))

In [9]:
def log_scale_data (data, mini, maxi):
    data = np.where(data < mini, mini, data)
    data = np.where(data > maxi, maxi, data)
    data = np.log10(data)
    return data

def remove_outliers (data, mini, maxi):
    data = np.where(data < mini, mini, data)
    data = np.where(data > maxi, maxi, data)
    return data

In [11]:
objects_catalog = "som_objects_catalog.hdf5"
fits_catalog = "som_fits_catalog.hdf5"
catalog_path = os.path.join(root_path, "data/processed")
filename = os.path.join(catalog_path, objects_catalog)

# For each ldac file, read each table of each ccd
for ldac_file in [f for f in os.listdir(data_path) if f.endswith(".ldac")]:
    fits_id, extension = os.path.splitext(ldac_file)
    ldac_path = os.path.join(data_path, ldac_file)
    ldac = fits.open(ldac_path)
    # print(ldac.info())
    ldac_tables = [hdu for hdu in ldac if isinstance(hdu, fits.BinTableHDU)]
    n_ccd = len(ldac_tables)
    fits_ = fits.open(os.path.join(data_path, fits_id+".fits.fz"))
    fits_catalog = Table(names=("fits_id", "filename", "n_ccd"), dtype=("S2", "S2", "i2"))
    fits_catalog.add_row([fits_id, fits_id+".fits.fz", n_ccd])
    for i in range(1, len(ldac)):
        if ldac[i].data is not None and ldac[i].data.shape[0] > 0:
            table = Table(ldac[i].data)
            table.add_column(fits_id, name="FITS_ID", index=0)
            table.add_column(i, name="CCD_ID", index=1)
            try:
                exptime = fits_[i].header["EXPTIME"]
            except:
                exptime = 30
            table.add_column(exptime, name="EXPTIME")
            # normalise data before their registration
            try:
                table["ISO0"] = log_scale_data(table["ISO0"], 0.00001, 10000)
                table["ELLIPTICITY"] = remove_outliers(table["ELLIPTICITY"], 0.00001, 1)
                table["EXPTIME"] = log_scale_data(exptime * np.abs(table["BACKGROUND"]/np.mean(table["BACKGROUND"])), 0.00001, 30)
                table["BACKGROUND"] = remove_outliers((table["BACKGROUND"]-np.mean(table["BACKGROUND"])/np.std(table["BACKGROUND"])), -2., 2.)
                # print("Updating catalog file in {}".format(data_path))
                table.write(filename, path=filename, format="hdf5", overwrite=True, append=True)
            except:
                # In case one the ldac tables is empty or corrupted, we skip it
                continue
    fits_.close()
    ldac.close()

[2787  683 2868 ...  521   24   11]
[2721 2497 2389 ...    6 5698    5]
[ 928 4301 3906 ...   60  151  110]
[2664 6151 4311 ... 5314 3589  716]
[ 2668 11758  7851 ...    23  3677   370]
[1863 1464 3342 ...    7  373 2371]
[3067 2653  626 ...    5   15  261]
[ 1405   573 13157 ...    46   186   311]
[2661  564 2492 ...   24 1371 2464]
[ 1785  3642 14061 ...   487   533   423]
[5309 2524 6588 ...    8    5   12]
[6683 1503 1138 ...   61   17   14]
[2965 2207 5738 ...   50   17 1761]
[1341  568  336 ...    5   40 3384]
[2803 1767 3023 ...  192    6  115]
[7610 3857 8056 ...   89   24  478]
[  304 15726 37035 ...   134   220  9741]
[1001 1616 5439 ...   14    7    7]
[  747 16606 87318 ...     9   213  1500]
[  984  1115 38350 ...     5     6   571]
[9974  985 6825 ...   13 1217   94]
[2188  268 1526 ...   50   24   10]
[ 890  847 2449 ...    5  797  122]
[3797   18 2022 ... 1216    8 1475]
[ 3026 11623  2166 ...   946   143     9]
[1822 3562 1163 ...    7   11    6]
[32386 10654 15504 ...

KeyError: "Key 'ISO0' does not exist."